version: 2.1
orbs:
  slack-notifier: martyzz1/slack-notifier@4.2.0
workflows:
  send-notification:
    jobs:
      - slack-notifier/slack-workflow-monitor:
          context: slack-notifications
          giphy-failure-keyword: broken
          giphy-success-keyword: party
          workflow-name: send-notification