version: 2.1
orbs:
  slack-notifier: martyzz1/slack-notifier@4.2.0

jobs:
  build-and-test:
    macos:
      xcode: 13.4.1
    steps:
      - run:
          name: Install Dependencies
          command: sleep 5
      - run:
          name: Symlink python
          command: sleep 1
      - run:
          name: Check python version
          command: python -V
      - run:
          name: Setup WN in known hosts
          command: sleep 1 
      - run:
          name: Clone SDK
          command: sleep 5 
      - run:
          name: Build SDK
          command: sleep 10
      - run:
          name: Store Artifacts
          command: sleep 2


workflows:
  build-and-notify:
    jobs:
      - slack-notifier/slack-workflow-monitor:
          context: slack-notifications
          giphy-failure-keyword: broken
          giphy-success-keyword: party
          workflow-name: build-and-notify
      - build-and-test